# Generated by Django 4.2.7 on 2024-01-04 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=100)),
                ('sage', models.IntegerField()),
                ('sgender', models.CharField(max_length=100)),
                ('scourse', models.CharField(max_length=100)),
                ('saddress', models.CharField(max_length=100)),
                ('spassword', models.CharField(max_length=100)),
            ],
        ),
    ]
